# Build stage
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env .
RUN npm run lint && npm run build

# Taking the builder for making tests
# FROM builder AS tester

# Development stage
FROM node:22-alpine AS development
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env .

ARG GROUPNAME=truckbusters-group
ARG USERNAME=truckbusters-app-user
ARG USER_GID=1002
ARG USER_UID=1002

RUN addgroup -g $USER_GID -S $GROUPNAME \
    && adduser -u $USER_UID -S -G $GROUPNAME $USERNAME

RUN chown -R $USERNAME:$GROUPNAME /app

USER $USERNAME

CMD ["node","server.js"]

# # Production stage
# FROM node:22-alpine AS production
# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install --only=production
# COPY --from=build /app/dist /app/dist
# COPY --from=build /app/package.json ./
# COPY .env .

# ARG GROUPNAME=truckbusters-group
# ARG USERNAME=truckbusters-app-user
# ARG USER_GID=1002
# ARG USER_UID=1002

# RUN addgroup -g $USER_GID -S $GROUPNAME \
#     && adduser -u $USER_UID -S -G $GROUPNAME $USERNAME

# RUN chown -R $USERNAME:$GROUPNAME /app

# USER $USERNAME

# CMD ["node","server.js"]
