FROM node:22-alpine
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
COPY .env .

ARG GROUPNAME=truckbusters-group
ARG USERNAME=truckbusters-app-user
ARG USER_GID=1002
ARG USER_UID=1002

RUN addgroup -g $USER_GID -S $GROUPNAME \
    && adduser -u $USER_UID -S -G $GROUPNAME $USERNAME

RUN chown -R $USERNAME:$GROUPNAME /app

USER $USERNAME

CMD ["node","server.js"]
