name: CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/22-cicd'
  pull_request:

jobs:
  push_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Create .env file
      run: |
        touch .env
        echo "${{secrets.ENV}}" >> .env 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TRUCKBUSTERS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.api
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/truckbusters-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/truckbusters-backend:${{ github.sha }}

  vps_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: SSh deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_KEY  }}
          script: |
            cd /test_app
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TRUCKBUSTERS_TOKEN }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
            sudo docker stop main  true
            sudo docker rm main  true
            sudo docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/truckbusters-backend:latest


            
      


